
# This model was used to successfully train a binary model.

batch_size: 48
# class_weights: True    # useful for non-binary, continuous models
# class_weights_loss_function:  /functions/default.class_weights_loss_function.py
data_file_training: '/path/to/the/data/file.csv'
data_file_prediction: null
data_bin_labels:          # there will be 2 for a binary model, and more for non-binary continuous
  - 'down'
  - 'up'
epochs: 500
learning_rate: 0.0012
loss_function: 'binary_crossentropy'
# extra_records_random_quantity: 0.2     # An amount, 0 to 1, indicating how many extra records should be read from the data file on each training run. 0 is none, 0.2 is up to 20% and 1 is up to twice the amount normally read#
metrics:
  - 'precision'
  - 'accuracy'
  - 'recall'
  - 'mae'
timesteps: 12
# use_online_learning: False
y-timeperiods: [1]

model_architecture:
  - layer_type: LSTM
    units: 120 
    return_sequences: False 
  - layer_type: Dense
    units: 1
    activation: 'sigmoid'  


# Data Features
features:
  - name: moving_average
    params:
      periods: [7, 21, 52]
      include_differences: True
  - name: rsi
    params:
      periods: [7, 17]



